services:
  postgres:
    image: postgres:16-alpine
    container_name: lojinha_db
    environment:
      POSTGRES_DB: lojinha_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lojinha-network

networks:
  lojinha-network:
    driver: bridge

volumes:
  postgres_data: